version: 2
updates:

- package-ecosystem: "npm"
  directory: "/client"
  schedule:
    interval: "daily"
- package-ecosystem: "npm"
  directory: "/auth"
  schedule:
    interval: "daily"
- package-ecosystem: "npm"
  directory: "/orders"
  schedule:
    interval: "daily"
- package-ecosystem: "npm"
  directory: "/tickets"
  schedule:
    interval: "daily"

- package-ecosystem: "docker"
  directory: "/client"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/auth"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/orders"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/tickets"
  schedule:
    interval: "daily"
