services:
  auth:
    image: mohakhlf/ticket-microservice-auth
    build:
      context: auth
      dockerfile: Dockerfile
  client:
    image: mohakhlf/ticket-microservice-client
    build:
      context: client
      dockerfile: Dockerfile
  tickets:
    image: mohakhlf/ticket-microservice-tickets
    build:
      context: tickets
      dockerfile: Dockerfile
  orders:
    image: mohakhlf/ticket-microservice-orders
    build:
      context: orders
      dockerfile: Dockerfile