services:
  auth:
    image: mohakhlf/ticket-microservice-auth
    build:
      context: auth
      dockerfile: Dockerfile
  client:
    image: mohakhlf/ticket-microservice-client
    build:
      context: client
      dockerfile: Dockerfile