apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: udemy-microservice-ticket
build:
  local:
    push: false
  artifacts:
  - image: mohakhlf/ticket-microservice-auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
deploy:
  kubectl:
    manifests:
    - infra/k8s/*
